#! /bin/bash -Ceu
###########################################################################
# test 1.0
#
# Copyright (C) 2013 - 2022 Eero Häkkinen <Eero+ldap-shadow@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
me=$( command -v -- "${0}" || ls -d -- "${0}" )
dir=$( dirname -- "${me}" )
wrapper=${dir}/bin/ldap-passwd
${LDAP_HAS_FRONTEND:+:} exec "${wrapper}" --mode=frontend "${0}" "${@}"
spawn() { ( set -x && exec "${@}" ); }
cd -- "${dir}"
GROUP=${GROUP-$( id -gn )}
OPTS=${OPTS-}
SERVICE=${SERVICE-WebSSO}
USER=${USER-$( id -un )}
LOGNAME=${LOGNAME-${USER}}
GROUP_DN_SPEC=$(
	ldapsearch -LLLM ${LDAPSEARCH_OPTS} \
		-a always \
		-o ldif-wrap=no \
		-z 1 \
		-- "(&(objectClass=posixGroup)(cn=${GROUP}))" 1.1 \
	| sed -e '/^dn:/!d' -e 'q'
	)
case ${GROUP_DN_SPEC} in
'dn:: '* ) GROUP_DN=$( echo "${GROUP_DN_SPEC#"dn:: "}" | base64 -d ) ;;
'dn: '*  ) GROUP_DN=${GROUP_DN_SPEC#"dn: "} ;;
*        ) GROUP_DN= ;;
esac
USER_DN_SPEC=$(
	ldapsearch -LLLM ${LDAPSEARCH_OPTS} \
		-a always \
		-o ldif-wrap=no \
		-z 1 \
		-- "(&(objectClass=posixAccount)(uid=${USER}))" 1.1 \
	| sed -e '/^dn:/!d' -e 'q'
	)
case ${USER_DN_SPEC} in
'dn:: '* ) USER_DN=$( echo "${USER_DN_SPEC#"dn:: "}" | base64 -d ) ;;
'dn: '*  ) USER_DN=${USER_DN_SPEC#"dn: "} ;;
*        ) USER_DN= ;;
esac
case ${USER_DN} in
*,uid="${LOGNAME}",* ) PRIMARY_USER_DN=uid=${LOGNAME},${USER_DN#*,uid="${LOGNAME}",} ;;
*                    ) PRIMARY_USER_DN= ;;
esac
SERVICE_USER_DN_SPEC=${SERVICE+$(
	ldapsearch -LLLM ${LDAPSEARCH_OPTS} \
		-b "${PRIMARY_USER_DN:-${USER_DN}}" \
		-o ldif-wrap=no \
		-z 1 \
		-- "(&(objectClass=organizationalRole)(ou:dn:=${SERVICE})(roleOccupant=${PRIMARY_USER_DN:-${USER_DN}}))" 1.1 \
	| sed -e '/^dn:/!d' -e 'q'
	)}
case ${SERVICE_USER_DN_SPEC} in
'dn:: '* ) SERVICE_USER_DN=$( echo "${SERVICE_USER_DN_SPEC#"dn:: "}" | base64 -d ) ;;
'dn: '*  ) SERVICE_USER_DN=${SERVICE_USER_DN_SPEC#"dn: "} ;;
*        ) SERVICE_USER_DN= ;;
esac
ADMIN_DN=$( exec "${wrapper}" --mode=binddn-admin )
for opts in \
	-{-add-attribute{=,' '},A{,' '}}ATTR=VALUE		\
	-{-binddn{=,' '},b{,' '}}primary			\
	-{-delete-attribute{=,' '},D{,' '}}ATTR{,=VALUE}	\
	-{-replace-attribute{=,' '},M{,' '}}ATTR{,=VALUE}	\
	-{-full-name{=,' '},f{,' '}}optarg			\
	-{-help,u}						\
	-{-home-phone{=,' '},h{,' '}}optarg			\
	-{-mobile-phone{=,' '},m{,' '}}optarg			\
	-{-room{=,' '},r{,' '}}optarg				\
	-{-root{=,' '},R{,' '}}optarg				\
	-{-service{=,' '},s{,' '}}"${SERVICE:-SKIP}"		\
	-{-version,V}						\
	-{-work-phone{=,' '},w{,' '}}optarg
do
	case ${opts} in *SKIP ) continue ;; esac
	spawn ./bin/ldap-chfn --dry-run --full-name=optarg ${opts} ${OPTS}
	spawn ./bin/ldap-chfn --dry-run --full-name=optarg ${opts} ${OPTS} "${USER}"
	spawn ./bin/ldap-chfn --dry-run --full-name=optarg ${opts} ${OPTS} "${USER_DN}"
	case ${PRIMARY_USER_DN:++} in
	+ ) spawn ./bin/ldap-chfn --dry-run --full-name=optarg ${opts} ${OPTS} "${PRIMARY_USER_DN}" ;;
	esac
	case ${opts} in --service[=\ ]* | -s* ) continue ;; esac
	case ${SERVICE_USER_DN:++} in
	+ ) spawn ./bin/ldap-chfn --dry-run --full-name=optarg ${opts} ${OPTS} "${SERVICE_USER_DN}" ;;
	esac
done > /dev/null
for opts in \
	-{-binddn{=,' '},b{,' '}}primary	\
	-{-help,h}				\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-shell{=,' '},s{,' '}}optarg		\
	-{-version,V}
do
	spawn ./bin/ldap-chsh --dry-run --shell=optarg ${opts} ${OPTS}
	spawn ./bin/ldap-chsh --dry-run --shell=optarg ${opts} ${OPTS} "${USER}"
	spawn ./bin/ldap-chsh --dry-run --shell=optarg ${opts} ${OPTS} "${USER_DN}"
done > /dev/null
for opts in \
	-{-binddn{=,' '},b{,' '}}primary		\
	-{-delete,d}					\
	-{-expire,e}					\
	-{-help,h}					\
	-{-inactive{=,' '},i{,' '}}optarg		\
	-{-maxdays{=,' '},x{,' '}}optarg		\
	-{-mindays{=,' '},n{,' '}}optarg		\
	-{-quiet,q}					\
	-{-repository{=,' '},r{,' '}}optarg		\
	-{-root{=,' '},R{,' '}}optarg			\
	-{-service{=,' '},s{,' '}}"${SERVICE:-SKIP}"	\
	-{-verbose,v}					\
	-{-version,V}					\
	-{-warndays{=,' '},w{,' '}}optarg
do
	case ${opts} in *SKIP ) continue ;; esac
	spawn ./bin/ldap-passwd --dry-run --maxdays=optarg ${opts} --quiet ${OPTS}
	spawn ./bin/ldap-passwd --dry-run --maxdays=optarg ${opts} --quiet ${OPTS} "${USER}"
	spawn ./bin/ldap-passwd --dry-run --maxdays=optarg ${opts} --quiet ${OPTS} "${USER_DN}"
	case ${PRIMARY_USER_DN:++} in
	+ ) spawn ./bin/ldap-passwd --dry-run --maxdays=optarg ${opts} --quiet ${OPTS} "${PRIMARY_USER_DN}" ;;
	esac
	case ${opts} in --service[=\ ]* | -s* ) continue ;; esac
	case ${SERVICE_USER_DN:++} in
	+ ) spawn ./bin/ldap-passwd --dry-run --maxdays=optarg ${opts} --quiet ${OPTS} "${SERVICE_USER_DN}" ;;
	esac
	spawn ./bin/ldap-passwd --dry-run --maxdays=optarg ${opts} --quiet ${OPTS} "${ADMIN_DN}"
done > /dev/null
for opts in \
	-{-help,h}	\
	-{-version,V}	\
	--
do
	spawn ./bin/ldap-pwqgen ${opts} ${OPTS}
	spawn ./bin/ldap-pwqgen ${opts} ${OPTS} random=96
done > /dev/null
for opts in \
	-{-force,f}				\
	-{-gid{=,' '},g{,' '}}optarg		\
	-{-help,h}				\
	-{-key{=,' '},K{,' '}}KEY=VALUE		\
	-{-non-unique,o}			\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-system,r}				\
	-{-version,V}
do
	spawn ./sbin/ldap-groupadd --dry-run ${opts} ${OPTS} "${GROUP}"
	spawn ./sbin/ldap-groupadd --dry-run ${opts} ${OPTS} "${GROUP_DN}"
done > /dev/null
for opts in \
	-{-help,h}				\
	-{-key{=,' '},K{,' '}}KEY=VALUE		\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-version,V}
do
	spawn ./sbin/ldap-groupdel --dry-run ${opts} ${OPTS} "${GROUP}"
	spawn ./sbin/ldap-groupdel --dry-run ${opts} ${OPTS} "${GROUP_DN}"
done > /dev/null
for opts in \
	-{-add{=,' '},a{,' '}}optarg		\
	-{-delete{=,' '},d{,' '}}optarg		\
	-{-gid{=,' '},g{,' '}}optarg		\
	-{-help,h}				\
	-{-key{=,' '},K{,' '}}KEY=VALUE		\
	-{-members{=,' '},M{,' '}}optarg	\
	-{-new-name{=,' '},n{,' '}}optarg	\
	--new-superior-dn{=,' '}optarg		\
	-{-non-unique,o}			\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-version,V}
do
	spawn ./sbin/ldap-groupmod --dry-run ${opts} ${OPTS} "${GROUP}"
	spawn ./sbin/ldap-groupmod --dry-run ${opts} ${OPTS} "${GROUP_DN}"
done > /dev/null
for opts in \
	-{-base-dir{=,' '},b{,' '}}optarg	\
	-{-comment{=,' '},c{,' '}}optarg	\
	-{-expiredate{=,' '},e{,' '}}1		\
	-{-gid{=,' '},g{,' '}}12345		\
	-{-groups{=,' '},G{,' '}}optarg		\
	-{-help,h}				\
	-{-home{,-dir}{=,' '},d{,' '}}optarg	\
	-{-inactive{=,' '},f{,' '}}optarg	\
	-{-key{=,' '},K{,' '}}KEY=VALUE		\
	-{-no-create-home,M}			\
	-{-no-log-init,l}			\
	-{-no-user-group,N}			\
	-{-non-unique,o}			\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-shell{=,' '},s{,' '}}optarg		\
	-{-system,r}				\
	-{-uid{=,' '},u{,' '}}optarg		\
	-{-user-group,U}			\
	-{-version,V}
do
	spawn ./sbin/ldap-useradd --dry-run ${opts} ${OPTS} "${USER}"
	spawn ./sbin/ldap-useradd --dry-run ${opts} ${OPTS} --gid=12345 "${USER_DN}"
done > /dev/null
for opts in \
	-{-help,h}				\
	-{-key{=,' '},K{,' '}}KEY=VALUE		\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-version,V}
do
	spawn ./sbin/ldap-userdel --dry-run ${opts} ${OPTS} "${USER}"
	spawn ./sbin/ldap-userdel --dry-run ${opts} ${OPTS} "${USER_DN}"
done > /dev/null
for opts in \
	-{-add-attribute{=,' '},A{,' '}}ATTR=VALUE		\
	-{-delete-attribute{=,' '},D{,' '}}ATTR{,=VALUE}	\
	-{-replace-attribute{=,' '},M{,' '}}ATTR{,=VALUE}	\
	-{-append,a}						\
	-{-comment{=,' '},c{,' '}}optarg			\
	-{-expiredate{=,' '},e{,' '}}1				\
	-{-gid{=,' '},g{,' '}}12345				\
	-{-groups{=,' '},G{,' '}}optarg				\
	-{-help,h}						\
	-{-home{,-dir}{=,' '},d{,' '}}optarg			\
	-{-inactive{=,' '},f{,' '}}optarg			\
	-{-key{=,' '},K{,' '}}KEY=VALUE				\
	-{-login{=,' '},l{,' '}}optarg				\
	--new-superior-dn{=,' '}optarg				\
	-{-non-unique,o}					\
	-{-root{=,' '},R{,' '}}optarg				\
	-{-shell{=,' '},s{,' '}}optarg				\
	-{-uid{=,' '},u{,' '}}optarg				\
	-{-version,V}
do
	spawn ./sbin/ldap-usermod --dry-run ${opts} ${OPTS} "${USER}"
	spawn ./sbin/ldap-usermod --dry-run ${opts} ${OPTS} "${USER_DN}"
done > /dev/null
