#! /bin/bash -Ceu
me=$( which -- "${0}" || ls -d -- "${0}" )
dir=$( dirname -- "${me}" )
wrapper=${dir}/bin/ldap-passwd
${LDAP_HAS_FRONTEND:+:} exec "${wrapper}" --mode=frontend "${0}" "${@}"
spawn() { ( set -x; exec "${@}" ); }
cd -- "${dir}"
GROUP=${GROUP-$( id -gn )}
USER=${USER-$( id -un )}
for opts in \
	-{-add-attribute{=,' '},A{,' '}}ATTR=VALUE		\
	-{-delete-attribute{=,' '},D{,' '}}ATTR{,=VALUE}	\
	-{-replace-attribute{=,' '},M{,' '}}ATTR{,=VALUE}	\
	-{-full-name{=,' '},f{,' '}}optarg			\
	-{-help,u}						\
	-{-home-phone{=,' '},h{,' '}}optarg			\
	-{-mobile-phone{=,' '},m{,' '}}optarg			\
	-{-room-number{=,' '},r{,' '}}optarg			\
	-{-root{=,' '},R{,' '}}optarg				\
	-{-version,V}						\
	-{-work-phone{=,' '},w{,' '}}optarg
do
	spawn ./bin/ldap-chfn --dry-run --full-name=optarg ${opts}
done 3> /dev/null
for opts in \
	-{-help,h}			\
	-{-root{=,' '},R{,' '}}optarg	\
	-{-shell{=,' '},s{,' '}}optarg	\
	-{-version,V}
do
	spawn ./bin/ldap-chsh --dry-run --shell=optarg ${opts}
done 3> /dev/null
for opts in \
	-{-delete,d}				\
	-{-expire,e}				\
	-{-help,h}				\
	-{-inactive{=,' '},i{,' '}}optarg	\
	-{-maxdays{=,' '},x{,' '}}optarg	\
	-{-mindays{=,' '},n{,' '}}optarg	\
	-{-quiet,q}				\
	-{-repository{=,' '},r{,' '}}optarg	\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-service{=,' '},s{,' '}}optarg	\
	-{-version,V}				\
	-{-warndays{=,' '},w{,' '}}optarg
do
	spawn ./bin/ldap-passwd --dry-run --maxdays=optarg ${opts}
done 3> /dev/null
for opts in \
	-{-force,f}				\
	-{-gid{=,' '},g{,' '}}optarg		\
	-{-help,h}				\
	-{-key{=,' '},K{,' '}}KEY=VALUE		\
	-{-non-unique,o}			\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-system,r}				\
	-{-version,V}
do
	spawn ./sbin/ldap-groupadd --dry-run ${opts} "${GROUP}"
done 3> /dev/null
for opts in \
	-{-help,h}				\
	-{-key{=,' '},K{,' '}}KEY=VALUE		\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-version,V}
do
	spawn ./sbin/ldap-groupdel --dry-run ${opts} "${GROUP}"
done 3> /dev/null
for opts in \
	-{-add{=,' '},a{,' '}}optarg		\
	-{-delete{=,' '},d{,' '}}optarg		\
	-{-gid{=,' '},g{,' '}}optarg		\
	-{-help,h}				\
	-{-key{=,' '},K{,' '}}KEY=VALUE		\
	-{-members{=,' '},M{,' '}}optarg	\
	-{-new-name{=,' '},n{,' '}}optarg	\
	--new-superior-dn{=,' '}optarg		\
	-{-non-unique,o}			\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-version,V}
do
	spawn ./sbin/ldap-groupmod --dry-run ${opts} "${GROUP}"
done 3> /dev/null
for opts in \
	-{-base-dir{=,' '},b{,' '}}optarg	\
	-{-comment{=,' '},c{,' '}}optarg	\
	-{-expiredate{=,' '},e{,' '}}1		\
	-{-gid{=,' '},g{,' '}}12345		\
	-{-groups{=,' '},G{,' '}}optarg		\
	-{-help,h}				\
	-{-home{,-dir}{=,' '},d{,' '}}optarg	\
	-{-inactive{=,' '},f{,' '}}optarg	\
	-{-key{=,' '},K{,' '}}KEY=VALUE		\
	-{-no-create-home,M}			\
	-{-no-log-init,l}			\
	-{-no-user-group,N}			\
	-{-non-unique,o}			\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-shell{=,' '},s{,' '}}optarg		\
	-{-system,r}				\
	-{-uid{=,' '},u{,' '}}optarg		\
	-{-user-group,U}			\
	-{-version,V}
do
	spawn ./sbin/ldap-useradd --dry-run ${opts} "${USER}"
done 3> /dev/null
for opts in \
	-{-help,h}				\
	-{-key{=,' '},K{,' '}}KEY=VALUE		\
	-{-root{=,' '},R{,' '}}optarg		\
	-{-version,V}
do
	spawn ./sbin/ldap-userdel --dry-run ${opts} "${GROUP}"
done 3> /dev/null
for opts in \
	-{-add-attribute{=,' '},A{,' '}}ATTR=VALUE		\
	-{-delete-attribute{=,' '},D{,' '}}ATTR{,=VALUE}	\
	-{-replace-attribute{=,' '},M{,' '}}ATTR{,=VALUE}	\
	-{-append,a}						\
	-{-comment{=,' '},c{,' '}}optarg			\
	-{-expiredate{=,' '},e{,' '}}1				\
	-{-gid{=,' '},g{,' '}}12345				\
	-{-groups{=,' '},G{,' '}}optarg				\
	-{-help,h}						\
	-{-home{,-dir}{=,' '},d{,' '}}optarg			\
	-{-inactive{=,' '},f{,' '}}optarg			\
	-{-key{=,' '},K{,' '}}KEY=VALUE				\
	-{-login{=,' '},l{,' '}}optarg				\
	--new-superior-dn{=,' '}optarg				\
	-{-non-unique,o}					\
	-{-root{=,' '},R{,' '}}optarg				\
	-{-shell{=,' '},s{,' '}}optarg				\
	-{-uid{=,' '},u{,' '}}optarg				\
	-{-version,V}
do
	spawn ./sbin/ldap-usermod --dry-run ${opts} "${USER}"
done 3> /dev/null
