#! /bin/sh -Cefu
###########################################################################
# ldap-groupdel 1.0
#
# Copyright (C) 2012 - 2015 Eero Häkkinen <Eero+ldap-shadow@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
wrapper=${0%ldap-*}ldap-groupadd
case ${1-} in
--help=man        ) exec "${0}" --help=troff | exec man -l -- -; exit ;;
--help=troff      ) exec help2man -L 'en_US.UTF-8' -N -n 'delete an LDAP POSIX group' -s 8 -- "${0}" ;;
--help=* | --help ) exec cat << __USAGE__ ;;
Usage: ${0##*[\\/]} [OPTION]... GROUP

Delete an LDAP POSIX group from an LDAP server using administrative privileges.

Options:
 -h, --help[=FORMAT]    Show this help message and exit.
 -K, --key KEY=VALUE    Override a default configuration.
 -R, --root CHROOT_DIR  (ignored)
 -V, --version          Show version information and exit.
     --dry-run          Dump LDIF and exit.

Operands:
 GROUP            The name (the common name defined by cn attribute) of
                  the LDAP POSIX group which is to be deleted using
                  administrative privileges.

Environment:
 LDAPBINDDN       A distinguished name (DN) to be used for binding to an LDAP
                  server. The default is to search for a distinguished name
                  (DN) based on the current real username.
 LDAPBINDPW       A password for the distinguished name (DN) to be used for
                  binding to an LDAP server. The default is to prompt for
                  a password.
 LDAPCONF         A system LDAP configuration file.
 LDAPRC           A user LDAP configuration file.
 LDAPURI          An URI of an LDAP server or a list of URIs of LDAP servers.
 LDAPMODIFY_OPTS  Options for ldapmodify(1).
 LDAPSEARCH_OPTS  Options for ldapsearch(1).
 LOGNAME          A username.
 SUDO_USER        A real username.
 USER             A fallback username.

Files:
 /etc/ldap/ldap.conf  LDAP configuration. See also ldap.conf(5).

__USAGE__
--version ) unset LDAP_HAS_FRONTEND ;;
esac
${LDAP_HAS_FRONTEND:+:} exec "${wrapper}" --mode=frontend "${0}" "${@}"

###########################################################################
#
# Options.
#
###########################################################################
while getopts hK:R:V-: OPT "${@}"
do
	case -${OPT}${OPTARG-} in
	--key | --root )
		OPT=${OPT}${OPTARG}
		eval 'OPTARG=${'"${OPTIND}"'?}'
		OPTIND=$(( ${OPTIND} + 1 ))
		;;
	--*=* ) OPT=${OPT}${OPTARG%%=*} OPTARG=${OPTARG#*=} ;;
	--*   ) OPT=${OPT}${OPTARG%%=*}; unset OPTARG ;;
	esac
	case -${OPT}${OPTARG+=} in
	--help    | -h* | \
	--help=   ) exec "${0}" --help"${OPTARG+=${OPTARG}}" >&3 ;;
	--key=    | -K* ) eval "${OPTARG%%=*}"='${OPTARG#*=}' ;;
	--root=   | -R* ) ;;
	--version | -V* ) exec "${0}" --version >&3 ;;
	--dry-run ) exec >&3 ;;
	--*       ) OPTIND=1; getopts '' OPT "--${OPTARG-}"; exit 1 ;;
	*         ) exit 1 ;;
	esac
done
shift $(( $OPTIND - 1 ))
GROUP=${1-}
: "${GROUP:?}"

# LDAPBINDDN.
LDAPBINDDN=${LDAPBINDDN-$( exec "${wrapper}" --mode=binddn-admin )}
case ${LDAPBINDDN:++} in
+ ) export LDAPBINDDN; printf '# ,,,[%s],,,\n' "LDAPBINDDN=${LDAPBINDDN}" ;;
esac

###########################################################################
#
# Values.
#
###########################################################################
# GROUP_DN_SPEC.
case ${GROUP} in
*=* ) GROUP_DN_SPEC=$(
	ldapsearch -LLLM ${LDAPSEARCH_OPTS} \
		-b "${GROUP}" \
		-o ldif-wrap=no \
		-s base \
		-- '(objectClass=posixGroup)' 1.1 \
	| sed -e '/^dn:/!d' -e 'q'
	) ;;
*   ) GROUP_DN_SPEC=$(
	ldapsearch -LLLM ${LDAPSEARCH_OPTS} \
		-o ldif-wrap=no \
		-z 1 \
		-- "(&(objectClass=posixGroup)(cn=${GROUP}))" 1.1 \
		2> /dev/null \
	| sed -e '/^dn:/!d' -e 'q'
	) ;;
esac
: "${GROUP_DN_SPEC:?}"

###########################################################################
#
# LDIF.
#
###########################################################################
# GROUP.
cat << __LDIF__
${GROUP_DN_SPEC}
changetype: delete

__LDIF__
