#! /bin/sh -Cefu
###########################################################################
# ldap-groupdel 1.0
#
# Copyright (C) 2012 Eero Häkkinen <Eero+ldap-shadow@Häkkinen.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################
unfold() { exec sed -e ': in' -e 'N' -e 's/\n //' -e 't in' -e 'P' -e 'D'; }
case ${1-} in
--help ) exec cat << __USAGE__ ;;
Usage: ${0##*[\\/]} [OPTION]... GROUP

Delete an LDAP group from an LDAP server using administrative privileges.

Options:
 -h, --help           Display this help message and exit.
 -K, --key KEY=VALUE  Override a default configuration.
     --dry-run        Dump LDIF and exit.

Operands:
 GROUP            The name (the common name defined by cn attribute) of
                  the LDAP group which is to be deleted using administrative
                  privileges.

Environment:
 LDAPBINDDN       A distinguished name (DN) to be used for binding to an LDAP
                  server. The default is to search for a distinguished name
                  (DN) based on the current real username.
 LDAPBINDPW       A password for the distinguished name (DN) to be used for
                  binding to an LDAP server. The default is to prompt for
                  a password.
 LDAPCONF         A system LDAP configuration file.
 LDAPRC           A user LDAP configuration file.
 LDAPURI          An URI of an LDAP server or a list of URIs of LDAP servers.
 LDAPMODIFY_OPTS  Options for ldapmodify(1).
 LDAPSEARCH_OPTS  Options for ldapsearch(1).
 LOGNAME          A username.
 SUDO_USER        A real username.
 USER             A fallback username.

Files:
 /etc/ldap/ldap.conf  LDAP configuration. See also ldap.conf(5).

__USAGE__
esac
${LDAP_HAS_FRONTEND:+:} exec "${0%ldap-*}ldap-groupadd" --mode=frontend "${0}" "${@}"

###########################################################################
#
# Options.
#
###########################################################################
while getopts hK:-: OPT "${@}"
do
	case -${OPT}${OPTARG-} in
	--key )
		OPT=${OPT}${OPTARG}
		eval 'OPTARG=${'"${OPTIND}"'?}'
		OPTIND=$(( ${OPTIND} + 1 ))
		;;
	--*=* ) OPT=${OPT}${OPTARG%%=*} OPTARG=${OPTARG#*=} ;;
	--*   ) OPT=${OPT}${OPTARG%%=*} OPTARG= ;;
	esac
	case -${OPT} in
	--help | -h ) exec "${0}" --help >&3 ;;
	--key  | -K ) eval "${OPTARG%%=*}"='${OPTARG#*=}' ;;
	--dry-run   ) exec >&3 ;;
	--*         ) OPTIND=1; getopts '' OPT "--${OPTARG-}"; exit 1 ;;
	*           ) exit 1 ;;
	esac
done
shift $(( $OPTIND - 1 ))
GROUP=${1-}
: "${GROUP:?}"

# LDAPBINDDN.
LDAPBINDDN=${LDAPBINDDN-$(
	printf '%s\n' "${SUDO_USER-${LOGNAME}}" 'admin' \
	| ldapsearch -LLLM ${LDAPSEARCH_OPTS} -f - -z 1 -- \
		"(&(objectClass=simpleSecurityObject)(cn=%s))" 1.1 \
		2> /dev/null \
	| unfold \
	| sed -e '/^dn: */!d' -e 's///' -e 'q'
	)}
case ${LDAPBINDDN:++} in
+ ) export LDAPBINDDN; printf '# LDAPBINDDN=%s\n' "${LDAPBINDDN}" ;;
esac

###########################################################################
#
# Values.
#
###########################################################################
# GROUP_DN.
GROUP_DN=${GROUP_DN-$(
	ldapsearch -LLLM ${LDAPSEARCH_OPTS} -z 1 -- \
		"(&(objectClass=posixGroup)(cn=${GROUP}))" 1.1 2> /dev/null \
	| unfold \
	| sed -e '/^dn: */!d' -e 's///' -e 'q'
	)}
: "${GROUP_DN:?}"

###########################################################################
#
# LDIF.
#
###########################################################################
# GROUP.
cat << __LDIF__
dn: ${GROUP_DN}
changetype: delete

__LDIF__
